[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn start"
  port = 3000

[context.production]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build"
  publish = "dist"

[context.branch-deploy]
  command = "yarn build"
  publish = "dist"
